Teste/Teste/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # URL padrão
    path('', include('app.urls', namespace='app')),

    # Interface administrativa
    path('admin/', admin.site.urls),
]

Teste/app/urls.py
"""
Definition of urls for Teste.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.urls import path
from app.views import (ListaPlayers, PlayerCreateView, CursosCreateView, InsereCursosForm, IndexTemplateView, ListaCursos, 
PlayerUpdate, CursosUpdate, PlayerDelete, CursoDelete
)
app_name = 'app'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    path('admin/', admin.site.urls),

    path('createP/', views.post_createPlayer, name="cadastra_player"),
    path('players/', ListaPlayers.as_view(), name ='lista_player'),
    path('players/<pk>', PlayerUpdate.as_view(), name ='update_player'),
    path('players/Delete/<pk>', PlayerDelete.as_view(), name ='delete_player'),


    path('createC/', views.post_create,  name="cadastra_curso"),
    path('cursos/', ListaCursos.as_view(), name ='lista_curso'),
    path('cursos/<pk>', CursosUpdate.as_view(), name ='update_curso'),
    path('cursos/Delete/<pk>', CursoDelete.as_view(), name ='delete_curso')   
    
]

Teste/app/templates/app/Cursos.html
{% extends "app/_layouts/base.html" %}

{% block title %}Lista de Cursos{% endblock %}

{% block conteudo %}
<div class="container-fluid ">
     <div class="row">
           
               <div class="card border-info mb-3" style="width: 180rem;height: 6rem">
        <div class="card-body">
         
             <a href="{% url 'app:cadastra_curso' %}"
                    class="btn btn-primary btn-lg btn-block btn-info">
                     <samp>Cadastro de Cursos</samp>
             </a>
         
        </div>
      </div>
            </div>
        </div>
    
<div class="container-fluid ">
  <div class="row">
   

          {% if Cursos|length > 0 %}
            <p class="card-text">
           <div class="table-responsive table-hover table-sm table table-striped">
            <table class="table">
              <thead class="thead-light">
              <tr>
                <th>Curso</th>
                <th class="text-center">Graduacao</th>
                <th>Materias</th>
                <th>Player</th>
                <th class="text-center" >Horas</th>
                <th class="text-center">Workshop</th>
                <th class="text-center">Implementacao</th>
                <th class="text-center">Comunik</th>
                <th class="table-info text-center">Opcoes</th>
              </tr>
              </thead>

              <tbody>
              {% for Cursos in Cursos%}
                <tr>
                  <td>{{ Cursos.nmCurso }}</td>
                  <td class="text-center">{{ Cursos.acFaculdade }}</td>
                  <td>{{ Cursos.nuMaterias }}</td>
                  <td>{{ Cursos.nmPlayer }}</td>
                  <td class="text-center" >{{ Cursos.nuHoras }}</td>
                  <td class="text-center">{{ Cursos.acWorkshop }}</td>
                  <td class="text-center">{{ Cursos.acImplementacao }}</td>
                  <td class="text-center">{{ Cursos.acComunik }}</td>
                  <td class="table-info text-center">
                    

                    <a href="{% url 'app:update_curso' pk=Cursos.id %}"
                       class="btn btn-info">
                      Atualizar
                    </a>
                    <a href="{% url 'app:delete_curso' pk=Cursos.id %}"
                      class="btn btn-outline-danger">
                        Excluir
                    </a>
                  <td>
                 
                  
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Cursos</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          
        </div>
       </div>
      </div>
  
{% endblock %}

Teste/app/templates/app/Players.html
{% extends "app/_layouts/base.html" %}

{% block title %}Lista de Players{% endblock %}

{% block conteudo %}
<div class="container-fluid ">
     <div class="row">
           
               <div class="card border-info mb-3" style="width: 180rem;height: 6rem">
        <div class="card-body">
         
             <a href="{% url 'app:cadastra_player' %}"
                    class="btn btn-primary btn-lg btn-block btn-info">
                     <samp>Cadastro de Players</samp>
             </a>
         
        </div>
      </div>
            </div>
        </div>
    
<div class="container-fluid ">
  <div class="row">
   

          {% if Players|length > 0 %}
            <p class="card-text">
           <div class="table-responsive table-hover table-sm table table-striped">
            <table class="table">
              <thead class="thead-light">
              <tr>
                <th>Player</th>
                <th>Link Imagem</th>
                <th class="text-center" >Setor</th>
                 <th class="table-info text-center">Opcoes</th>
              </tr>
              </thead>

              <tbody>
              {% for Players in Players%}
                <tr>
                  <td>{{ Players.nmcolaborador}}</td>
                  <td>{{ Players.imcolaborador}}</td>
                  <td class="text-center" >{{ Players.nmSetor }}</td>

                  <td class="table-info text-center">
                    

                    <a href="{% url 'app:update_player' pk=Players.id %}"
                       class="btn btn-info">
                      Atualizar
                    </a>
                    <a href="{% url 'app:delete_player' pk=Players.id %}"
                      class="btn btn-outline-danger">
                        Excluir
                    </a>
                  <td>
                 
                  
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Player</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
         
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Teste/app/templates/app/curso_delete.html
<!-- Estendemos do template base -->
{% extends "app/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa pagina -->
{% block title %}Pagina Inicial{% endblock %}

<!-- Bloco de conteudo da nossa pagina -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusao de Curso</h5>

        <p class="card-text">
          Voce tem certeza que quer excluir o Curso 
          <b>{{ cursos.nmCurso }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'app:lista_curso' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Teste/app/templates/app/curso_forms.html
{% extends "app/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Curso{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Curso</h5>
          <p class="card-text">
            Complete o formulario abaixo para cadastrar
            um novo <code>Curso</code>.
          </p>
          <form method="post">
            <!-- Nao se esqueca dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
        <div class="row">
                <div class="col-md-6 order-first">
            <div class="input-group mb-6">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome do Curso</span>
              </div>
              {% render_field form.nmCurso class+="form-control" %}
                     </div></div> 
              <!-- Remuneracao -->
            <div class="col-md-6 order-last">
                <div class="input-group mb-6">
              <div class="input-group-prepend">
                <span class="input-group-text">Player</span>
              </div>
              {% render_field form.nmPlayer class+="form-control" %}
             
            </div></div>
                   
        </div>
<div class="row align-items-center mt-3">
            <!-- Sobrenome -->
    <div class="col-md-3">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                  
                <span class="input-group-text">Faculdade/Tecnico?</span>
              </div>
        <div class="col-md-3">
              {% render_field form.acFaculdade class+="form-control" %}
                </div>      
            </div></div>

            <!-- CPF -->
     <div class="col-md-3 order">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Materias</span>
              </div>
              {% render_field form.nuMaterias class+="form-control" %}
            </div></div>

            <!-- Tempo de Servico -->
    <div class="col-md-6 order-last">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Qual instituicao?</span>
              </div>
              {% render_field form.nmInstituicao class+="form-control" %}
            </div></div>
    </div>


             <!-- Horas -->
        
             <!-- workshop -->
            <div class="input-group mb-3">

                <div class="input-group-prepend">
                <span class="input-group-text">Numero de Horas</span>
              </div>
              {% render_field form.nuHoras  class+="form-control" %}

              <div class="input-group-prepend">
                <span class="input-group-text">Fez workshop?</span>
              </div>
              {% render_field form.acWorkshop class+="form-control" %}

                <div class="input-group-prepend">
                <span class="input-group-text">Fez Implementacao?</span>
              </div>
              {% render_field form.acImplementacao class+="form-control" %}

                <div class="input-group-prepend">
                <span class="input-group-text">Fez Comunik?</span>
              </div>
               {% render_field form.acComunik class+="form-control" %}
              
            </div>


            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Teste/app/templates/app/curso_update.html
{% extends "app/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualizacao de Dados do Curso{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizacao de Dados do Curso</h5>          
          <form method="post">
              <!-- Nao se esqueca dessa tag -->
              {% csrf_token %}

      <!-- Nome -->
        <div class="row">
                <div class="col-md-6 order-first">
            <div class="input-group mb-6">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome do Curso</span>
              </div>
              {% render_field form.nmCurso class+="form-control" %}
                     </div></div> 
              <!-- Remuneracao -->
            <div class="col-md-6 order-last">
                <div class="input-group mb-6">
              <div class="input-group-prepend">
                <span class="input-group-text">Player</span>
              </div>
              {% render_field form.nmPlayer class+="form-control" %}
             
            </div></div>
                   
        </div>
<div class="row align-items-center mt-3">
            <!-- Sobrenome -->
    <div class="col-md-3">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                  
                <span class="input-group-text">Faculdade/Tecnico?</span>
              </div>
        <div class="col-md-3">
              {% render_field form.acFaculdade class+="form-control" %}
                </div>      
            </div></div>

            <!-- CPF -->
     <div class="col-md-3 order">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Materias</span>
              </div>
              {% render_field form.nuMaterias class+="form-control" %}
            </div></div>

            <!-- Tempo de Servico -->
    <div class="col-md-6 order-last">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Qual instituicao?</span>
              </div>
              {% render_field form.nmInstituicao class+="form-control" %}
            </div></div>
    </div>


             <!-- Horas -->
        
             <!-- workshop -->
            <div class="input-group mb-3">

                <div class="input-group-prepend">
                <span class="input-group-text">Numero de Horas</span>
              </div>
              {% render_field form.nuHoras  class+="form-control" %}

              <div class="input-group-prepend">
                <span class="input-group-text">Fez workshop?</span>
              </div>
              {% render_field form.acWorkshop class+="form-control" %}

                <div class="input-group-prepend">
                <span class="input-group-text">Fez Implementacao?</span>
              </div>
              {% render_field form.acImplementacao class+="form-control" %}

                <div class="input-group-prepend">
                <span class="input-group-text">Fez Comunik?</span>
              </div>
               {% render_field form.acComunik class+="form-control" %}
              
            </div>


            <button class="btn btn-primary">Enviar</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Teste/app/templates/app/index.html
<!-- Estendemos do template base -->
{% extends "app/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa pagina -->
{% block title %}Inicio{% endblock %}

<!-- Bloco de conteúdo da nossa pagina -->    
{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col order-first">
      <div class="card  text-center" style="width: 30rem;height: 6rem">
        <div class="card-body">
         
             <a href="{% url 'app:lista_curso' %}"
             class="btn btn-primary btn-lg btn-block btn-info">
            <samp>Lista de Cursos</samp>
          </a>
          <p class="card-text-center">
           <samp> Lista de</samp> <code>cursos</code> <samp>ja cadastrados.</samp>
          </p>
         
        </div>
      </div>
    </div>
      <div class="col order-last">
      <div class="card text-center" style="width: 30rem;height: 6rem">
        <div class="card-body">
         
             <a href="{% url 'app:lista_player' %}"
             class="btn btn-primary btn-lg btn-block btn-info">
            <samp>Lista de Players</samp>
          </a>
          <p class="card-text-center text-center">
           <samp> Lista de</samp> <code>players</code> <samp>ja cadastrados.</samp>
          </p>
         
        </div>
      </div>
    </div>
   </div> 
  </div>
<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <iframe width="1570" height="773" src="https://app.powerbi.com/reportEmbed?reportId=65fe1e7b-6a02-4fee-a5b0-1ea9dcda0fee&autoAuth=true&ctid=74f4d89d-d0f4-4a1f-b65f-afb854141b49&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLWJyYXppbC1zb3V0aC1yZWRpcmVjdC5hbmFseXNpcy53aW5kb3dzLm5ldC8ifQ%3D%3D" frameborder="0" allowFullScreen="true"></iframe>
    </div>

</div>
    </div>
{% endblock %}

Teste/app/templates/app/player_delete.html
<!-- Estendemos do template base -->
{% extends "app/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa pagina -->
{% block title %}Pagina Inicial{% endblock %}

<!-- Bloco de conteudo da nossa pagina -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusao de Player</h5>

        <p class="card-text">
          Voce tem certeza que quer excluir o Player 
          <b>{{ Player.nmcolaborador }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'app:lista_player' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Teste/app/templates/app/player_form.html
{% extends "app/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Player{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Player</h5>
          <p class="card-text">
            Complete o formulario abaixo para cadastrar
            um novo <code>Player</code>.
          </p>
          <form method="post">
            <!-- Nao se esqueca dessa tag -->
            {% csrf_token %}
<div class="row align-items-center mt-3">
            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nmcolaborador class+="form-control" %}
           
              <div class="input-group-prepend">
                <span class="input-group-text">Setor</span>
              </div>
              {% render_field form.nmSetor class+="form-control" %}
            
            </div></div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Link do avatar</span>
              </div>
              {% render_field form.imcolaborador class+="form-control" %}
            </div>

            <!-- CPF -->
            

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Teste/app/templates/app/player_update.html
{% extends "app/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualizacao de Dados do Player{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizacao de Dados do Player</h5>          
          <form method="post">
            <!-- Nao se esqueca dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome do Player</span>
              </div>
              {% render_field form.nmcolaborador class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Link da imagem do Player</span>
              </div>
              {% render_field form.imcolaborador class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Setor do Player</span>
              </div>
              {% render_field form.nmSetor class+="form-control" %}
            </div>
            <hr />
            <div class="text-right">
              <a href="{% url 'app:lista_player' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}