Teste/Teste/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    # URL padrão
    path('', include('app.urls', namespace='app')),

    # Interface administrativa
    path('admin/', admin.site.urls),
]

Teste/app/urls.py
"""
Definition of urls for Teste.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.urls import path
from app.views import (ListaPlayers, PlayerCreateView, CursosCreateView, InsereCursosForm, IndexTemplateView, ListaCursos, 
PlayerUpdate, CursosUpdate, PlayerDelete, CursoDelete
)
app_name = 'app'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),
    path('admin/', admin.site.urls),

    path('createP/', views.post_createPlayer, name="cadastra_player"),
    path('players/', ListaPlayers.as_view(), name ='lista_player'),
    path('players/<pk>', PlayerUpdate.as_view(), name ='update_player'),
    path('players/Delete/<pk>', PlayerDelete.as_view(), name ='delete_player'),


    path('createC/', views.post_create,  name="cadastra_curso"),
    path('cursos/', ListaCursos.as_view(), name ='lista_curso'),
    path('cursos/<pk>', CursosUpdate.as_view(), name ='update_curso'),
    path('cursos/Delete/<pk>', CursoDelete.as_view(), name ='delete_curso')   
    
]

Teste/app/templates/app/_layouts/base - Copy.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>

      <meta charset="iso-8859-1">
      <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <!-- Title -->
    <title>
      {% block title %}Sistema de Gerenciamento da Gameficacao TI{% endblock %}
    </title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'app/img/favicon.png' %}" type="image/png">

    <!-- Arquivos CSS -->
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/master.css' %}">

    <!-- Bloco de Estilos -->
    {% block styles %}{% endblock %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'app:index' %}">
          <img src="{% static 'app/img/favicon.png' %}" height='45'>
        </a>
        <button class="navbar-toggler" type="button" 
            data-toggle="collapse" data-target="#conteudo-navbar" 
            aria-controls="conteudo-navbar" aria-expanded="false" 
            aria-label="Ativar navegacao">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="conteudo-navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app:index' %}">
                      Inicio
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:lista_player' %}">
                      Players
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:cadastra_curso' %}">
                      Cursos
                    </a>
                </li>
            </ul>           
        </div>
    </nav>
      
    <!-- Bloco de contedo -->
    {% block conteudo %}{% endblock %}

    <!-- Arquivos necessarios para o Bootstrap -->
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.min.js' %}"></script>

    <!-- Bloco de scripts -->
    {% block scripts %}{% endblock %}

    <!-- Scripts.js -->
    <script src="{% static 'app/scripts/scripts.js' %}"></script>
  </body>
</html>

Teste/app/templates/app/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Collapsible sidebar using Bootstrap 3</title>
        <link rel="shortcut icon" href="{% static 'app/img/favicon.png' %}" type="image/png">
        <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
    
        <!-- Our Custom CSS -->
        <link rel="stylesheet" href="style2.css">
        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="{% static 'app/css/jquery.mCustomScrollbar.min.css' %}">

<style>
  
  /*
    DEMO STYLE
*/
@import "app/content/css.css";


body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
}

p {
    font-family: 'Poppins', sans-serif;
    font-size: 1.1em;
    font-weight: 300;
    line-height: 1.7em;
    color: #999;
}

a, a:hover, a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
}

.navbar {
    padding: 15px 10px;
    background: #fff;
    border: none;
    border-radius: 0;
    margin-bottom: 40px;
    box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
}

.navbar-btn {
    box-shadow: none;
    outline: none !important;
    border: none;
}

.line {
    width: 100%;
    height: 1px;
    border-bottom: 1px dashed #ddd;
    margin: 40px 0;
}

/* ---------------------------------------------------
    SIDEBAR STYLE
----------------------------------------------------- */
#sidebar {
    width: 200px;
    position: fixed;
    top: 0;
    left: 0;
    height: 100vh;
    z-index: 999;
    background: #7386D5;
    color: #fff;
    transition: all 0.3s;
}

#sidebar.active {
    margin-left: -250px;
}

#sidebar .sidebar-header {
    padding: 20px;
    background: #6d7fcc;
}

#sidebar ul.components {
    padding: 20px 0;
    border-bottom: 1px solid #47748b;
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
}
#sidebar ul li a:hover {
    color: #7386D5;
    background: #fff;
}

#sidebar ul li.active > a, a[aria-expanded="true"] {
    color: #fff;
    background: #6d7fcc;
}


a[data-toggle="collapse"] {
    position: relative;
}

a[aria-expanded="false"]::before, a[aria-expanded="true"]::before {
    content: '\e259';
    display: block;
    position: absolute;
    right: 20px;
    font-family: 'Glyphicons Halflings';
    font-size: 0.6em;
}
a[aria-expanded="true"]::before {
    content: '\e260';
}


ul ul a {
    font-size: 0.9em !important;
    padding-left: 30px !important;
    background: #6d7fcc;
}

ul.CTAs {
    padding: 20px;
}

ul.CTAs a {
    text-align: center;
    font-size: 0.9em !important;
    display: block;
    border-radius: 5px;
    margin-bottom: 5px;
}
a.download {
    background: #fff;
    color: #7386D5;
}
a.article, a.article:hover {
    background: #6d7fcc !important;
    color: #fff !important;
}


/* ---------------------------------------------------
    CONTENT STYLE
----------------------------------------------------- */
#content {
    width: calc(100% - 250px);
    padding: 40px;
    min-height: 100vh;
    transition: all 0.3s;
    position: absolute;
    top: 0;
    right: 0;
}
#content.active {
    width: 100%;
}


/* ---------------------------------------------------
    MEDIAQUERIES
----------------------------------------------------- */
@media (max-width: 768px) {
    #sidebar {
        margin-left: -250px;
    }
    #sidebar.active {
        margin-left: 0;
    }
    #content {
        width: 100%;
    }
    #content.active {
        width: calc(100% - 250px);
    }
    #sidebarCollapse span {
        display: none;
    }
}

</style>
    </head>
    <body>


        
        <div class="wrapper">
           

            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3><img src="{% static 'app/img/favicon.png' %}" height='130' width="160">  </h3>
                </div>

                <ul class="list-unstyled components">
                    
                    <li class="active">
                        <a href ="{% url 'app:index' %}"> Inicio</a>
                        
                    </li>
                    <li class="active">
                        <a href ="{% url 'app:lista_player' %}"> Players</a>
                        
                    </li>
                      <li class="active">
                        <a href ="{% url 'app:lista_curso' %}"> Cursos</a>
                        
                    </li>
                     
                 
                    
                    
                </ul>

                
            </nav>
            



            <!-- Page Content Holder -->
            <div id="content">
               
                
                <!--<nav class="navbar navbar-default">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <i class="glyphicon glyphicon-align-left"></i>
                                <span>Toggle Sidebar</span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="#">Page</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>  -->

            <div class="row align-items-center"><div class="col">{% block conteudo %}{% endblock %}</div></div>
            </div>


        </div>

        



        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
               

                $('#sidebarCollapse').on('click', function () {
                    $('#sidebar, #content').toggleClass('active');
                    $('.collapse.in').toggleClass('in');
                    $('a[aria-expanded=true]').attr('aria-expanded', 'false');
                });
            });
        </script>
    </body>
</html>